listen: :8443

tls:
  cert: /cert/server.crt
  key: /cert/server.key

auth:
  type: password
  password: 

obfs:
  type: salamander
  salamander:
    password: ""

masquerade:
  type: proxy
  proxy:
    url: https://www.bing.com
    rewriteHost: true
  listenHTTP: :80
  listenHTTPS: :443  
  forceHTTPS: true

ignoreClientBandwidth: true
