services:
  hysteria2:
    image: tobyxdd/hysteria:latest
    container_name: hysteria2
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - $PWD/config.yaml:/etc/hysteria/config.yaml
      - /cert:/cert
    command: server -c /etc/hysteria/config.yaml
